### ISSUE TITLE
Pass JWT to Trellis

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_server#43] opened 2019-02-07 19:20 UTC
For a resource stored in Trellis, store a user's WebID in a Group container's ACL,

**Comment by jmartin-sul** [comment] 2019-02-07 21:37
see also #42.  not sure if this is a duplicate of that?  that ticket is really just about "given the webid, write some JS client code to update an ACL", but there's also the obtaining-the-webID part, which this ticket title touches on more.

**Comment by jmartin-sul** [comment] 2019-03-11 19:24
per this trellis documentation, we'll want to do this by passing the entire JWT to trellis in the auth header:
> A JWT token appears in a header as:
> 
> ```
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3ZWJpZCI6Imh0dHA6Ly9leGFtcGxlLmNvbS91c2VyIn0.YyVrlxXVQXFtg6euOl7I1GTMwdm7SiHcIZb6L0brBqI
> ```
> 
  - https://github.com/trellis-ldp/trellis/wiki/Authentication#jwt-authentication

trellis is then configured to decode and validate the JWT, and to use the webID provided therein if the JWT is valid.

see also:
https://github.com/trellis-ldp/trellis/tree/master/auth/oauth
https://github.com/trellis-ldp/trellis/wiki/App-Configuration-Guide

**Comment by jmartin-sul** [comment] 2019-03-11 19:35
due to slowly shifting title, it seems i accidentally repurposed what started out as an ACL update ticket, and turned it into something about generally passing the JWT to trellis.

i'll open a new ticket for the latter issue (what my last comment was about).

since it seems like #42 adequately captured the beginnings of our ACL editing work, i'm just going to close this ticket.

**Closed by jmartin-sul** 2019-03-11 19:35 UTC
Labels: Sinopia JS client, Sinopia Server, in progress

**Comment by jmartin-sul** [comment] 2019-03-11 19:39
feel free to reopen and edit if i got this wrong.
